/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionBar: (typeof import('./../lib/comp/alarm-dialog-cnt/components/alarm-detail/ActionBar.vue'))['default']
    AlarmClose: (typeof import('./../lib/comp/alarm-close/AlarmClose.vue'))['default']
    AlarmConfirm: (typeof import('./../lib/comp/alarm-confirm/AlarmConfirm.vue'))['default']
    AlarmCount: (typeof import('./../lib/views/components/alarm-count.vue'))['default']
    AlarmDetail: (typeof import('./../lib/comp/alarm-dialog-cnt/components/alarm-detail/index.vue'))['default']
    AlarmDialog: (typeof import('./../lib/views/components/alarm-dialog.vue'))['default']
    AlarmDialogCnt: (typeof import('./../lib/comp/alarm-dialog-cnt/alarm-dialog-cnt.vue'))['default']
    AlarmHelper: (typeof import('./../lib/views/alarm-helper.vue'))['default']
    AlarmList: (typeof import('./../lib/comp/alarm-dialog-cnt/components/alarm-list/alarm-list.vue'))['default']
    AlarmMenuItem: (typeof import('./../lib/comp/alarm-menu-item/AlarmMenuItem.vue'))['default']
    AlarmMsgList: (typeof import('./../lib/comp/alarm-dialog-cnt/components/alarm-list/alarm-msg-list.vue'))['default']
    AlarmWS: (typeof import('./../lib/comp/alarm-ws/AlarmWS.vue'))['default']
    Attachment: (typeof import('./../lib/comp/alarm-dialog-cnt/components/alarm-detail/Attachment.vue'))['default']
    AudioBox: (typeof import('./../lib/comp/audio-box/AudioBox.vue'))['default']
    ConstantList: (typeof import('./../lib/comp/alarm-dialog-cnt/components/menu-list/components/constant-list.vue'))['default']
    ControlStra: (typeof import('./../lib/comp/alarm-dialog-cnt/components/alarm-detail/ControlStra.vue'))['default']
    DeatilCommon: (typeof import('./../lib/comp/alarm-dialog-cnt/components/alarm-detail/DeatilCommon.vue'))['default']
    DetailSect: (typeof import('./../lib/comp/alarm-dialog-cnt/components/alarm-detail/DetailSect.vue'))['default']
    ElIcon: (typeof import('element-plus/es'))['ElIcon']
    ElImage: (typeof import('element-plus/es'))['ElImage']
    ElImageViewer: (typeof import('element-plus/es'))['ElImageViewer']
    ExpandBtn: (typeof import('./../lib/comp/alarm-dialog-cnt/components/menu-list/components/expand-btn.vue'))['default']
    FallbackBox: (typeof import('./../lib/comp/fallback-box/FallbackBox.vue'))['default']
    FallBackList: (typeof import('./../lib/comp/alarm-dialog-cnt/components/alarm-detail/FallBackList.vue'))['default']
    FilterBox: (typeof import('./../lib/comp/alarm-dialog-cnt/components/alarm-list/filter-box.vue'))['default']
    ImageBox: (typeof import('./../lib/comp/image-box/ImageBox.vue'))['default']
    LiveBox: (typeof import('../lib/comp/live-box/LiveBox-aliplayer.vue'))['default']
    LivePlay: (typeof import('./../lib/comp/alarm-dialog-cnt/components/alarm-detail/LivePlay.vue'))['default']
    MenuList: (typeof import('./../lib/comp/alarm-dialog-cnt/components/menu-list/menu-list.vue'))['default']
    MenuPanel: (typeof import('./../lib/comp/alarm-dialog-cnt/components/menu-list/components/menu-panel.vue'))['default']
    PicCapture: (typeof import('./../lib/comp/alarm-dialog-cnt/components/alarm-detail/PicCapture.vue'))['default']
    RecordBox: (typeof import('./../lib/comp/record-box/RecordBox.vue'))['default']
    RecordPlay: (typeof import('./../lib/comp/alarm-dialog-cnt/components/alarm-detail/RecordPlay.vue'))['default']
    Remark: (typeof import('./../lib/comp/alarm-dialog-cnt/components/alarm-detail/Remark.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    SwiperBox: (typeof import('./../lib/comp/swiper-box/SwiperBox.vue'))['default']
  }
}
