import { AxiosResponse } from 'axios';
declare const service: import('axios').AxiosInstance;
export declare function getBaseUrl(): string;
export declare function getRealUrl(api: string): string;
export declare const casGet: (url: any, params: any) => Promise<AxiosResponse<any, any>>;
export declare const casPost: (url: string, params?: any, tout?: number) => Promise<AxiosResponse<any, any>>;
export declare function get<R>(url: string, params?: any): Promise<R>;
export declare function post<R>(url: string, params?: any, tout?: number): Promise<R>;
export declare function postJson<R>(url: string, params?: any): Promise<R>;
export declare function postJsonParams<R>(url: string, params?: any): Promise<R>;
export declare function postFormat<R>(url: string, params?: any, tout?: number): Promise<R>;
export declare function put<R>(url: string, params?: any): Promise<R>;
export declare function put_form<R>(url: string, params?: any, tout?: number): Promise<R>;
export declare function del<R>(url: string, params?: any, tout?: number): Promise<R>;
export declare function getExport<R>(url: string, params?: any, tout?: number): Promise<R>;
export declare function getFile<R>(url: string, headers?: any): Promise<R>;
export declare function postFile<R>(url: string, params?: any): Promise<R>;
export declare function uploadFile<R>(url: string, params?: any): Promise<R>;
export declare function uploadImportFile<R>(url: string, params?: any, tout?: number): Promise<R>;
export declare function put_post<R>(url: any, params: any): Promise<R>;
export declare function del_post<R>(url: any, tout?: number): Promise<R>;
export default service;
